version: '3.6'
services:
  coinos-cd-app:
    container_name: coinos-cd-app

  nginx-ssl-proxy: #< automatic SSL
    depends_on:
    - nginx
    container_name: nginx-ssl-proxy
    image: danieldent/nginx-ssl-proxy
    environment:
      UPSTREAM: 'coinos-cd-app' #< send traffic to service above
      SERVERNAME: cd.coinos.io
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/etc/letsencrypt